title: Josep Rodriguez
google_analytics: UA-52154663-2
theme: jekyll-theme-minimal
name: Josep Rodriguez
markdown: kramdown

bookmark:
  - name: Home page
    url: /
  - name: View My Portfolio
    url: /portfolio
  - name: View My Resume
    url: /resume
