# title: Josep Rodriguez
# description: I am a Mobile Senior Software Engineer who strives for well crafted software, CI&CD to deliver value to organisations.
# github_username:  joseprl89
# linkedin_username:  joseprl89

theme: minimal
